captainVersion: 4
services:
    $$cap_appname:
        image: docker.flipt.io/flipt/flipt:$$cap_ant_version
        volumes:
            - $$cap_appname-data:/var/opt/flipt
            - $$cap_appname-config:/etc/flipt
        restart: always
        ports:
            - '9000:9000'

        caproverExtra:
            containerHttpPort: 8080
caproverOneClickApp:
    variables:
        - id: $$cap_ant_version
          label: Flipt Version
          description: Choose the latest version of Flipt to deploy
          defaultValue: latest
    instructions:
        start: |-
            Enterprise-ready, GitOps enabled, CloudNative feature management solution
        end: |-
            You can access Flipt at http://$$cap_appname.$cap_root_domain

            To get started, please refer to the documentation at https://flipt.io/docs.
    displayName: Flipt
    isOfficial: false
    description: Enterprise-ready, GitOps enabled, CloudNative feature management solution
