captainVersion: 4
services:
    $$cap_appname-postgres:
        image: postgres:latest
        restart: always
        volumes:
            - $$cap_appname-postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: $$cap_postgres_user
            POSTGRES_PASSWORD: $$cap_postgres_password
            POSTGRES_DB: peppermint
        caproverExtra:
            containerHttpPort: 5432
            notExposeAsWebApp: true

    $$cap_appname:
        image: pepperlabs/peppermint:latest
        restart: always
        ports:
            - 5003:5003
        healthcheck:
            test: ['CMD', 'sh', '-c', 'wget --spider $$BASE_URL']
            interval: 30s
            timeout: 10s
            retries: 3
        environment:
            DB_USERNAME: $$cap_postgres_user
            DB_PASSWORD: $$cap_postgres_password
            DB_HOST: srv-captain--$$cap_appname-postgres
            SECRET: $$cap_secret
            API_URL: $$cap_appname.$$cap_root_domain
        caproverExtra:
            containerHttpPort: 3000

caproverOneClickApp:
    variables:
        - id: $$cap_postgres_user
          label: PostgreSQL Username
          defaultValue: 'postgres'
          description: PostgreSQL Username
          validRegex: /^([^\s^\/])+$/

        - id: $$cap_postgres_password
          label: PostgreSQL Password
          defaultValue: $$cap_gen_random_hex(32)
          description: PostgreSQL Password
          validRegex: /^([^\s^\/])+$/

        - id: $$cap_secret
          label: Secret
          defaultValue: $$cap_gen_random_hex(32)
          description: Secret
          validRegex: /^([^\s^\/])+$/
    instructions:
        start: |-
            Control your customer support
            In a world of ever growing costs, Peppermint is here to help.
        end: |-
            Peppermint is now running on your Captain Instance!

            You can access it via the following URL: http://$$cap_appname.$$cap_root_domain

            The default username and password are: admin@admin.com / 1234
    displayName: Peppermint
    isOfficial: false
    description: Control your customer support. In a world of ever growing costs, Peppermint is here to help.
