captainVersion: 4
services:
    $$cap_appname-mysql:
        image: mysql:8.0-oracle
        environment:
            MYSQL_DATABASE: zabbix
            MYSQL_USER: "zabbix"
            MYSQL_PASSWORD: $$cap_db_root_password
            MYSQL_ROOT_PASSWORD: $$cap_db_root_password
            MYSQL_COLLATION_SERVER: utf8_bin
            MYSQL_CHARACTER_SET_SERVER: utf8
        volumes:
            - $$cap_appname-db-data:/var/lib/mysql
        restart: always
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname-gateway:
        image: zabbix/zabbix-java-gateway:alpine-$$cap_zabbix_version
        restart: always
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname-server:
        image: zabbix/zabbix-server-mysql:alpine-$$cap_zabbix_version
        environment:
            DB_SERVER_HOST: srv-captain--$$cap_appname-mysql
            MYSQL_DATABASE: "zabbix"
            MYSQL_USER: "zabbix"
            MYSQL_PASSWORD: $$cap_zabbix_pwd
            MYSQL_ROOT_PASSWORD: $$cap_db_root_password
            ZBX_JAVAGATEWAY: srv-captain--$$cap_appname-gateway
        volumes:
            - $$cap_appname-server-alertscripts:/usr/lib/zabbix/alertscripts
            - $$cap_appname-server-externalscripts:/usr/lib/zabbix/externalscripts
            - $$cap_appname-server-modules:/var/lib/zabbix/modules
            - $$cap_appname-server-enc:/var/lib/zabbix/enc
            - $$cap_appname-server-mibs:/var/lib/zabbix/mibs
        restart: always
        ports:
            - '10051:10051'
        caproverExtra:
            notExposeAsWebApp: 'true'

    $$cap_appname:
        image: zabbix/zabbix-web-nginx-mysql:alpine-$$cap_zabbix_version
        environment:
            ZBX_SERVER_HOST: srv-captain--$$cap_appname-server
            DB_SERVER_HOST: srv-captain--$$cap_appname-mysql
            MYSQL_DATABASE: "zabbix"
            MYSQL_USER: "zabbix"
            MYSQL_PASSWORD: $$cap_zabbix_pwd
            MYSQL_ROOT_PASSWORD: $$cap_db_root_password
            PHP_TZ: $$cap_php_timezone
        restart: always
        caproverExtra:
            containerHttpPort: '80'

caproverOneClickApp:
    variables:
        - id: $$cap_zabbix_version
          label: Zabbix Version
          defaultValue: '6.4-latest'
          description: Check out the Zabbix Docker page for the valid tags https://hub.docker.com/r/zabbix/zabbix-web-nginx-mysql/tags/
          validRegex: /^([^\s^\/])+$/

        - id: $$cap_php_timezone
          label: Timezone
          defaultValue: 'America/New_York'
          description: Timezone

        # MYSQL
        - id: $$cap_db_root_password
          label: MySQL Root Password
          defaultValue: $$cap_gen_random_hex(32)
          description: MySQL Root Password

        - id: $$cap_zabbix_pwd
          label: Zabbix Password
          defaultValue: $$cap_gen_random_hex(32)
          description: Zabbix Password
    displayName: Zabbix
    isOfficial: false
    description: Zabbix is a powerful open-source monitoring solution for keeping tabs on your infrastructure's health and performance.
    documentation: https://www.zabbix.com/documentation/